name: paylog
description: A friendly payment tracking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  pdf: ^3.10.4
  printing: ^5.10.2
  intl: 0.20.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  share_plus: ^7.0.0
  file_picker: ^10.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/